### ISSUE TITLE
[🐞] AuthorizeActionSuccess is nil, can't read transaction infos

### ISSUE THREAD

**Issue by AndrexOfficial** [paypal/paypalcheckout-ios#51]
### 🐞 Describe the Bug
The AuthorizeActionSuccess is retuned nil by the SDK and the payment is not successful.

### 🔬 Minimal Reproduction
Tap on PayPal button, the view appears, you select a payment method and tap on continue, the view dismiss with no successful payment.

### 😕 Actual Behavior
The SDK calls "approval.actions.authorize { success, error in" closure with error not nil and success nil and return "OrderActionError 1" in error.localizedDescription.
It seems it does not read the returnURL correctly, I'm using a wrapper view that behaves as button and puts out some delegates for successful payment or failed payment.
I tried to put the config file on AppDelegate and does not work.

### 🤔 Expected Behavior
The SDK should call "approval.actions.authorize { success, error in" closure with error nil and success with AuthorizeActionSuccess model and dismiss for completed payment

### 🌍 Environment

- iOS version: 14.5
- SDK version (`Checkout.version`): 0.55.0

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by jonathajones** [comment]
Hi Andrex -
Thanks for opening a separate issue! First question: how are you creating the token / orderID that you are passing to the `createOrder` callback?

**Comment by AndrexOfficial** [comment]
Hello Jon, 
I'm creating the orderId from createOrder callback and I noticed a really strange thing: with version 0.51.0 it works with no problems, with the latest version it does not and shows me an errorGeneratingLSAT domain error code: -999.
It seems a request error and so that's why the AuthorizeActionSuccess is always nil.

```
po error
▿ Optional<Error>
  ▿ some : OrderActionError
    ▿ errorGeneratingLSAT : RequestError
      - other : Error Domain=NSURLErrorDomain Code=-999 "annullato" UserInfo={NSErrorFailingURLStringKey=https://www.sandbox.paypal.com/graphql, NSErrorFailingURLKey=https://www.sandbox.paypal.com/graphql, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <05D16E6A-7640-4F31-BA64-543D70AC68EF>.<127>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <05D16E6A-7640-4F31-BA64-543D70AC68EF>.<127>, NSLocalizedDescription=annullato}
```

**Comment by jonathajones** [comment]
Gotcha, understood - I believe this might be the result of a race condition. I'm working on a fix now that I believe will address  your issue. I'll let you know when to expect it in a release.

**Comment by AndrexOfficial** [comment]
Hello Jon, thanks for your reply, in the meanwhile I will use SDK v. 0.51.0 that seems to work without problems.

I have 3 questions for You:

1) Is it possibile to deactivate shipping address selection or pass a custom shipping address to the SDK?
2) Can I treat the PaymentButton as a classic UIButton and set a custom target for a tap (that will show a terms & conditions modal view) and then replace the target again in order to start the checkout SDK flow?
3) The PaymentButton how can it be customised? Cause on the documentation it does not tell anything about that nor on project examples.

Thanks a lot :)

**Comment by jonathajones** [comment]
Hi @AndrexOfficial - 
Great questions - 
1. Yes - this can be done by updating the `applicationContext` value during order creation (when you get the order ID that you end up passing to the SDK). You can find more information here: https://developer.paypal.com/docs/api/orders/v2/#definition-order_application_context
2. The `PaymentButton` type is a UIButton subclass. It already has an target registered on it, and tap gestures received by the payment button itself are not intended to be intercepted. 
3. The `PaymentButton` type can be thought of as an abstract class - the types you will likely want to use instead are `PayPalButton` or `PayPalPayLaterButton`. These button types can be visually customized through their initializers, where they take `color`, `edges` and `size` as parameters

**Comment by AndrexOfficial** [comment]
Hello Jon, thanks for your great replies.

I used `PayPalButton` and seems to work good, I created a wrapper that handles everything and acts as a View with the `PayPalButton` inside with top, bottom, leading and trailing to 0 related to the view, so I can place it everywhere.

I still have 2 questions (sorry about that):

1. Can I place multiple PayPalButtons inside a single view or inside the same class? declaring each button with: `var paymentButton = PayPalButton()`
2. So there is no way to use a `PayPalButton` as a standard button without starting the SDK checkout when it is pressed? Cause as I told You before I need to implement an express checkout feature that If I tap on the `PayPalButton` first it will shows a view with a terms and conditions flag and then If I tap another `PayPalButton` inside that view it will start the SDK checkout experience.

Thanks in advance for your patience :)

**Comment by minhthenguyen** [comment]
Hi @AndrexOfficial 
1. You can place multiple PayPalButtons inside a single view/class
2. Unfortunately we decide not to support that to keep our checkout experience consistent.
Please let us know if you have further questions.

**Comment by jaxdesmarais** [comment]
Hello @AndrexOfficial - 

The following error has been resolved in the latest release (0.66.0):
```
po error
▿ Optional<Error>
  ▿ some : OrderActionError
    ▿ errorGeneratingLSAT : RequestError
      - other : Error Domain=NSURLErrorDomain Code=-999 "annullato" UserInfo={NSErrorFailingURLStringKey=https://www.sandbox.paypal.com/graphql, NSErrorFailingURLKey=https://www.sandbox.paypal.com/graphql, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <05D16E6A-7640-4F31-BA64-543D70AC68EF>.<127>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <05D16E6A-7640-4F31-BA64-543D70AC68EF>.<127>, NSLocalizedDescription=annullato}
```
Please update to the latest version of the SDK to resolve this error and thanks for your patience! If you continue to run into issues after updating to the latest SDK version of 0.66.0, please feel free to reopen this issue.

**Comment by AndrexOfficial** [comment]
Hello, I tried with the latest version and I still see this error when I try use use ".authorize" method.
Any idea?

Thanks

**Comment by jonathajones** [comment]
Sorry @AndrexOfficial  - our mistake.  Version 0.66.0 is now deployed on CocoaPods. 

Could you post the full error message you're seeing?

**Comment by AndrexOfficial** [comment]
The issue seems ok now, I used the .xcframework.

With CocoaPods I'm having the same issue, 0.66.0 can't be found.

```
[!] CocoaPods could not find compatible versions for pod "PayPalCheckout":
  In Podfile:
    PayPalCheckout (= 0.66.0)

None of your spec sources contain a spec satisfying the dependency: `PayPalCheckout (= 0.66.0)`.
```

Best Regards

**Comment by jonathajones** [comment]
Is that using `pod install` or `pod update`? `0.66.0` is deployed on Cocoapods - you might need to run `pod update PayPalCheckout` to get the latest version.

**Comment by AndrexOfficial** [comment]
Hello Jon, 
I used `pod install` and tried also with `pod update` but still having problems, I'm using the `.xcframework` right now.

We started to test our app on iOS 15 Beta 8 and we noticed that the scroll on shipping addresses section does not work.
Are you planning to release a fully compatible version of your SDK with iOS 15? If yes when it should be released?

Best regards

**Comment by jonathajones** [comment]
Hi @AndrexOfficial  - Looking into it now, I'll update you when we have more info.

**Comment by jaxdesmarais** [comment]
Hello @AndrexOfficial -

I was able to test the current release of the SDK on the following devices + iOS versions and in all cases scroll is working as expected in the shipping address section:
| Device | iOS Version |
|----|----|
| Xcode 13 Beta Simulator | iOS 15.0 |
| iPhone 12 Pro | iOS 15 Public Beta 7 |
| iPhone 12 Pro | iOS 15 Beta 8 |

Would you be able to share the following details so we can troubleshoot further:
1. Device you are testing on.
2. Number of addresses saved to your PayPal account (note that if all addresses are displayed on the screen you would not be able to scroll as there would be no addresses out of the view).
3. Are other views outside of the paysheet addresses section scrolling as expected?

**Comment by AndrexOfficial** [comment]
Hello Jax,

I'm tested it on iPhone 12 Pro with iOS 15 Beta 8 and I noticed that it is not about the scroll but about the constraints of the container view that contains the tableView with the addresses, I attach a screenshot.

Thanks

![IMG_8741](https://user-images.githubusercontent.com/1239878/132825997-81b88359-c943-4447-9112-7c0e11418da3.jpg)

**Comment by jaxdesmarais** [comment]
Hello @AndrexOfficial -

Thanks for sending over those details. I was able to replicate this behavior on an account that had less addresses than what I was testing previously. We will work on a fix for this issues as it is limited to iOS 15. Thanks for reporting this issue and we will let you know when a fix is deployed to resolve this.

**Comment by AndrexOfficial** [comment]
Hello @jaxdesmarais,
Any update for the new release compatible with iOS 15?

Thanks

**Comment by jaxdesmarais** [comment]
Hello @AndrexOfficial we are planning to do a release with this fix included tomorrow. I will update you once the new version has been released.

**Comment by AndrexOfficial** [comment]
Hello @jaxdesmarais, keep me posted.

Thanks

**Comment by jaxdesmarais** [comment]
Hello @AndrexOfficial -

Version 0.70.0 has been released. The fix was tested on device as well as simulators running iOS 15. Please note there is also a new selector that you will see on the shipping addresses page in this version as well. Please let us know if you continue to see issues when updating to 0.70.0 and thanks again for your patience and reporting this issue!

**Comment by jaxdesmarais** [comment]
Hello @AndrexOfficial -

Version 0.70.0 has been released. The fix was tested on device as well as simulators running iOS 15. Please let us know if you continue to see issues when updating to 0.70.0 and thanks again for your patience and reporting this issue!

**Comment by AndrexOfficial** [comment]
Hello @jaxdesmarais, 
I tested it but the scrolling issue remains, I'm testing it on iPhone 13 Pro with iOS 15 build 19A346.

Can you check? Do you need more info about it?
If you want we can schedule a call in order to perform some tests
Thanks

**Comment by jaxdesmarais** [comment]
Hello @AndrexOfficial -

We've been able to replicate this on our end and are investigating further as we are seeing inconsistent behavior between our test app with the release and a new build with the release. I'll reach back out when we have an update.

**Comment by AndrexOfficial** [comment]
Hello @jaxdesmarais,
Thanks for keeping me posted about it, I also noticed another bug, if you swipe fast all left from the cell where you can add a new card you will see overlapped labels of shipping and conversion rate, I send you a screenshot.

Best regards

![IMG_0119 2](https://user-images.githubusercontent.com/1239878/135527720-dd2c9aaa-8aed-4b52-8e41-73885bee0f26.PNG)
ds

**Comment by minhthenguyen** [comment]
@AndrexOfficial 
Thank you for reporting the cell overlapping issue to us. This is a known bug which has been fixed from our side and will be in the next release version :smile:

**Comment by jaxdesmarais** [comment]
Hello @AndrexOfficial -

Thanks for your patience as we looked more into the TableView issue. As it stands currently, the parameter added to our SDK to fix this ([`sectionHeaderTopPadding`](https://developer.apple.com/documentation/uikit/uitableview/3750914-sectionheadertoppadding)) is only available in Swift 5.5. Our frameworks are built using Swift 5.3 to maintain backwards compatibility so this fix is not picked up when building our archives. I've ran some tests locally using SPM, Cocapods, and Carthage and including the following in my `AppDelegate`'s `didFinishLaunchingWithOptions` function:
```
if #available(iOS 15.0, *) {
    UITableView.appearance().sectionHeaderTopPadding = 0
}
```
If you are using a TableView elsewhere in your project and _do not_ wish to override this value in all cases, you can instead add the above to your class where you import `PayPalCheckout`. Would you mind testing the above on your end and letting me know the results? If you are seeing the same results of this fixing the issue, I will add this to our README.

**Comment by AndrexOfficial** [comment]
Hello @jaxdesmarais, thanks for your update, I will try it as soon as possible and let it know if it is fully fixed.

I have another question for You: Is it possible to change the order status once created from the SDK? cause we need to update the `invoice_id` into the `purchase_units` array, we perform a `getOrder` Rest API call from PayPal with the orderId created from the PayPal SDK but we need to update/add the `invoiceId` once payment is completed in order to link this PayPal's payment with the e-commerce's generated order number.

I tried to put a completion block between `.setCreateOrderCallback { createOrderAction in` and `createOrderAction.create(order: order) { orderId` but the SDK get stuck on a infinite loading spinner and does not show login flow or the view where you can choose the payment method.

Let me know,
Thanks
Best Regards
