### ISSUE TITLE
[🐞] Crash - hidden stack trace

### ISSUE THREAD

**Issue by quintonpryce** [paypal/paypalcheckout-ios#96]
### 🐞 Describe the Bug
Crashed: com.apple.NSURLSession-delegate
0  libswiftCore.dylib             0x388dc8 _swift_release_dealloc + 32
1  PayPalCheckout                 0x217aa0 _hidden#31948_ + 157 (__hidden#31974_:157)
2  PayPalCheckout                 0x21911c _hidden#3153_ + 4397437212 (__hidden#4351_:4397437212)
3  PayPalCheckout                 0x21c0fc _hidden#2360_ + 4397449468 (__hidden#1243_:4397449468)
4  PayPalCheckout                 0x278ec4 _hidden#36541_ + 65 (__hidden#36580_:65)
5  PayPalCheckout                 0x279e80 _hidden#25664_ + 121 (__hidden#1243_:121)
6  PayPalCheckout                 0x1bfa4c _hidden#25649_ + 4397070924 (__hidden#25686_:4397070924)
7  PayPalCheckout                 0x107b94 _hidden#12240_ + 56 (__hidden#12258_:56)
8  PayPalCheckout                 0x251090 _hidden#34417_ + 156 (__hidden#1462_:156)
9  PayPalCheckout                 0x25cbc8 _hidden#34550_ + 4397714376 (__hidden#1243_:4397714376)
10 PayPalCheckout                 0x251978 _hidden#34422_ + 4397668728
11 PayPalCheckout                 0x25e138 _hidden#34575_ + 4397719864
12 PayPalCheckout                 0x107d50 _hidden#12241_ + 61 (__hidden#12258_:61)
13 PayPalCheckout                 0x1c0a18 _hidden#25654_ + 121 (__hidden#25686_:121)
14 PayPalCheckout                 0x24bc20 _hidden#25657_ + 1376 (__hidden#34767_:1376)
15 PayPalCheckout                 0xf4e38 _hidden#10907_ + 122 (__hidden#7111_:122)
16 PayPalCheckout                 0xfd584 _hidden#11024_ + 4396275076
17 PayPalCheckout                 0xf4620 _hidden#10904_ + 4396238368 (__hidden#1243_:4396238368)
18 u1v1Me                         0x8472b4 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 307 (FPRNSURLSessionInstrument.m:307)
19 u1v1Me                         0x8472b4 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 307 (FPRNSURLSessionInstrument.m:307)
20 CFNetwork                      0x22b2c CFURLRequestSetMainDocumentURL + 3028
21 CFNetwork                      0x33bc0 _CFNetworkErrorCopyLocalizedDescriptionWithHostname + 11412
22 libdispatch.dylib              0x1c04 _dispatch_call_block_and_release + 32
23 libdispatch.dylib              0x3950 _dispatch_client_callout + 20
24 libdispatch.dylib              0xb0ac _dispatch_lane_serial_drain + 664
25 libdispatch.dylib              0xbc44 _dispatch_lane_invoke + 444
26 libdispatch.dylib              0x16318 _dispatch_workloop_worker_thread + 656
27 libsystem_pthread.dylib        0x11b0 _pthread_wqthread + 288
28 libsystem_pthread.dylib        0xf50 start_wqthread + 8

### 🌍 Environment

- iOS version: - iOS 15 only
- SDK version (`Checkout.version`): - 0.81.0

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by quintonpryce** [comment]
Let me know how I can be useful here, this is our second highest crash just under another one from this SDK.

**Comment by jonathajones** [comment]
Hi Quinton - would you be able to update to the latest version (`0.88.0`)? Since `0.81.0`, we've fixed a couple of different sources of crashes.

**Comment by jonathajones** [comment]
Hi @quintonpryce - Do you know when this first appeared? This is the same issue as https://github.com/paypal/paypalcheckout-ios/issues/99 . We're working on a strategy to desymbolicate the stack trace on our side - will update you here when that work is finished. Appreciate the patience.

**Comment by quintonpryce** [comment]
Thanks @jonathajones. Happy to help where I can. We are now on 0.84.0 and still seeing some hidden crashes. I will update the SDK on our next minor release.

**Comment by jonathajones** [comment]
Sounds great, and thanks @quintonpryce! we may take you up on your offer for feedback, by the way. As we move towards a 1.0 offering, we're going to focus more heavily on collecting developer experience feedback.

Once we start internally storing the dsym logs with our next version, we would need you to send us the crash report from Apple for us to desymbolicate. Alternatively, you could just provide us the partial crash file (with memory addresses from the crash within `PayPalCheckout`) that we would use to internally desymbolicate and triage. I'll let you know when we have the tools in place to handle this.

**Comment by jonathajones** [comment]
Hi @quintonpryce  - As of the latest release (0.94.0), we are now keeping and storing the dSYM files internally.

When you have crash reports in the future that have a _hidden trace (and are on version 0.94.0), you would send us either the full crash report, or the raw trace with the desymbolicated memory addresses. We can then symbolicate the stack on our end and better investigate the cause.
